name: Build and Push Backend Images on Tagging

on:
  push:

jobs:
  build:
    runs-on: 'zendesk-docker'
    steps:
    - uses: zendesk/checkout@v3    
    - name: Push to ECR
      uses: zendesk/docker-build-multiarch@v1
      with:
        image-name: "589470546847.dkr.ecr.us-west-2.amazonaws.com/compute-danswer-backend"        
        dockerfile: "./backend/Dockerfile"
        docker-args: ""
        working-directory: "./backend"
        additional-tag: ""
        architecture: "amd64"        
